version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/apps/redis-search-service
hooks:
  AfterInstall:
    - location: scripts/install_deps.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
